// Free-response practice: official-style prompts + the College Board scoring rubric structure.
// Rubric wording models the published scoring guidelines (which are open guidance); prompt source
// texts are original or public-domain so nothing copyrighted is redistributed. Drop real released
// prompts in here as they are published on AP Central.

export interface FrqRubricRow {
  /** Short label shown to the student, e.g. "Thesis / Claim". */
  name: string
  /** Points this row is worth (a 0–max band; the AI awards an integer in range). */
  maxPoints: number
  /** The exact criterion the response must meet to earn the point(s). */
  criteria: string
}

export interface FrqPrompt {
  id: string
  /** e.g. "Rhetorical Analysis", "Argument", "Synthesis", "Long Essay (LEQ)". */
  essayType: string
  title: string
  /** Released year or "Sample" — shown as a chip. */
  year?: string
  /** The task directions the student writes to. */
  directions: string
  /** Optional passage / source packet the response must engage with. */
  sourceText?: string
  /** College Board's suggested writing time, in minutes (drives the timer default). */
  suggestedMinutes: number
  /**
   * A "paste your finished work" task rather than a timed write — e.g. the AP Research academic
   * paper, graded holistically. When true the workspace hides the exam timer, accepts a much longer
   * response, and relabels the editor/CTA around pasting a completed paper.
   */
  longForm?: boolean
  rubric: FrqRubricRow[]
}

/** A College Board scored sample response for a released question (summary + score). */
export interface ReleasedFrqExample {
  /** e.g. "Sample 1A". */
  label: string
  /** Points the sample earned, as the official commentary scored it. */
  score: string | null
  /** Why it earned that score — the reader's rationale, summarized. */
  summary: string
  refId: string
}

/**
 * One question from a released AP exam (generated by tools/frq-release/build_frq_release.py).
 * The official booklet page(s) are shown as a PDF; the extracted text only feeds the grader.
 */
export interface ReleasedFrqQuestion {
  /** Stable prompt id — also tags this question's RAG rubric/exemplar chunks. */
  id: string
  /** Exams released in two sets (most subjects) number them 1 and 2; null when only one exists. */
  set: number | null
  /** e.g. "Q1", "SAQ 3", "DBQ", "LEQ 2", "Part A". */
  label: string
  /** Exam section heading where it matters (histories, AAS). */
  section: string | null
  essayType: string
  /** Short topic from the scoring guideline, when it adds something beyond essayType. */
  topic: string
  /** First line of the question, for the card. Null for math-heavy booklets (garbled extraction). */
  teaser: string | null
  suggestedMinutes: number
  totalPoints: number
  pdfUrl: string
  pageCount: number
  promptText: string
  sourceText: string | null
  /** Official scoring guideline summary for THIS question — sent to the grader and shown to students. */
  scoringGuide: string
  rubric: FrqRubricRow[]
  examples: ReleasedFrqExample[]
}

export interface ReleasedFrqSet {
  subjectName: string
  year: number
  questions: ReleasedFrqQuestion[]
}

export interface SubjectFrqSet {
  subjectName: string
  /** Provenance / usage note surfaced to the student. */
  note: string
  prompts: FrqPrompt[]
}
