// Emits V15__seed_sat_questions.sql from the bank JSON files.
//   node generate-seed.mjs
// Idempotent: overwrites the migration each run. Maps difficulty -> irt_b, fixes
// irt_a and irt_c per §4.6. Escapes all strings for Postgres.

import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const HERE = path.dirname(fileURLToPath(import.meta.url))
const BANK = path.join(HERE, '..', '..', 'server', 'src', 'main', 'resources', 'sat', 'bank')
const OUT = path.join(HERE, '..', '..', 'server', 'src', 'main', 'resources', 'db', 'migration',
  'V15__seed_sat_questions.sql')

const B = { easy: -1.0, medium: 0.0, hard: 1.0 }
const SKILL_FILES = [
  'arithmetic-percentages', 'algebra-equations', 'linear-functions', 'systems-of-equations',
  'quadratics-polynomials', 'exponential-functions', 'data-statistics', 'geometry-trigonometry',
]

const q = (s) => "'" + String(s).replace(/'/g, "''") + "'"       // SQL string literal
const jsonb = (v) => q(JSON.stringify(v)) + '::jsonb'

const rows = []
let total = 0, diag = 0
for (const skill of SKILL_FILES) {
  const d = JSON.parse(fs.readFileSync(path.join(BANK, `${skill}.json`), 'utf8'))
  for (const item of d.questions) {
    total++
    if (item.isDiagnostic) diag++
    const irtC = 0.25 // all v1 items are mc
    rows.push(
      '  (' + [
        q(item.id),
        q(d.skillId),
        item.stem == null ? 'NULL' : q(item.stem),
        q(item.explanation),
        q('mc'),
        jsonb(item.options),
        item.correctIndex,
        'NULL', // accepted_answers
        q(item.difficulty),
        '1.0',
        B[item.difficulty].toFixed(1),
        irtC.toFixed(2),
        item.isDiagnostic ? 'TRUE' : 'FALSE',
        item.source ? q(item.source) : 'NULL',
      ].join(', ') + ')')
  }
}

const header = `-- Seed the SAT question bank. Generated by tools/sat-import/generate-seed.mjs.
-- ${total} questions, ${diag} diagnostic. Do not hand-edit; re-run the generator.

INSERT INTO sat_questions
  (id, skill_id, stem, explanation, answer_type, options, correct_index,
   accepted_answers, difficulty, irt_a, irt_b, irt_c, is_diagnostic, source)
VALUES
`
fs.writeFileSync(OUT, header + rows.join(',\n') + ';\n')
console.log(`wrote ${OUT}`)
console.log(`${total} questions, ${diag} diagnostic`)
