// GENERATED by tools/generate-unit-bank.mjs — do not edit by hand.
import { BANK_AP_AFRICAN_AMERICAN_STUDIES } from './ap-african-american-studies'
import { BANK_AP_ART_HISTORY } from './ap-art-history'
import { BANK_AP_BIOLOGY } from './ap-biology'
import { BANK_AP_CALCULUS_AB } from './ap-calculus-ab'
import { BANK_AP_CALCULUS_BC } from './ap-calculus-bc'
import { BANK_AP_CHEMISTRY } from './ap-chemistry'
import { BANK_AP_COMPARATIVE_GOVERNMENT_AND_POLITICS } from './ap-comparative-government-and-politics'
import { BANK_AP_COMPUTER_SCIENCE_A } from './ap-computer-science-a'
import { BANK_AP_COMPUTER_SCIENCE_PRINCIPLES } from './ap-computer-science-principles'
import { BANK_AP_ENGLISH_LANGUAGE_AND_COMPOSITION } from './ap-english-language-and-composition'
import { BANK_AP_ENGLISH_LITERATURE_AND_COMPOSITION } from './ap-english-literature-and-composition'
import { BANK_AP_ENVIRONMENTAL_SCIENCE } from './ap-environmental-science'
import { BANK_AP_EUROPEAN_HISTORY } from './ap-european-history'
import { BANK_AP_HUMAN_GEOGRAPHY } from './ap-human-geography'
import { BANK_AP_MACROECONOMICS } from './ap-macroeconomics'
import { BANK_AP_MICROECONOMICS } from './ap-microeconomics'
import { BANK_AP_MUSIC_THEORY } from './ap-music-theory'
import { BANK_AP_PHYSICS_1 } from './ap-physics-1'
import { BANK_AP_PHYSICS_2 } from './ap-physics-2'
import { BANK_AP_PHYSICS_C_ELECTRICITY_AND_MAGNETISM } from './ap-physics-c-electricity-and-magnetism'
import { BANK_AP_PHYSICS_C_MECHANICS } from './ap-physics-c-mechanics'
import { BANK_AP_PRECALCULUS } from './ap-precalculus'
import { BANK_AP_PSYCHOLOGY } from './ap-psychology'
import { BANK_AP_RESEARCH } from './ap-research'
import { BANK_AP_SEMINAR } from './ap-seminar'
import { BANK_AP_STATISTICS } from './ap-statistics'
import { BANK_AP_UNITED_STATES_GOVERNMENT_AND_POLITICS } from './ap-united-states-government-and-politics'
import { BANK_AP_UNITED_STATES_HISTORY } from './ap-united-states-history'
import { BANK_AP_WORLD_HISTORY_MODERN } from './ap-world-history-modern'

import type { SubjectUnitBank } from './types'

export const UNIT_BANKS: SubjectUnitBank[] = [
  BANK_AP_AFRICAN_AMERICAN_STUDIES,
  BANK_AP_ART_HISTORY,
  BANK_AP_BIOLOGY,
  BANK_AP_CALCULUS_AB,
  BANK_AP_CALCULUS_BC,
  BANK_AP_CHEMISTRY,
  BANK_AP_COMPARATIVE_GOVERNMENT_AND_POLITICS,
  BANK_AP_COMPUTER_SCIENCE_A,
  BANK_AP_COMPUTER_SCIENCE_PRINCIPLES,
  BANK_AP_ENGLISH_LANGUAGE_AND_COMPOSITION,
  BANK_AP_ENGLISH_LITERATURE_AND_COMPOSITION,
  BANK_AP_ENVIRONMENTAL_SCIENCE,
  BANK_AP_EUROPEAN_HISTORY,
  BANK_AP_HUMAN_GEOGRAPHY,
  BANK_AP_MACROECONOMICS,
  BANK_AP_MICROECONOMICS,
  BANK_AP_MUSIC_THEORY,
  BANK_AP_PHYSICS_1,
  BANK_AP_PHYSICS_2,
  BANK_AP_PHYSICS_C_ELECTRICITY_AND_MAGNETISM,
  BANK_AP_PHYSICS_C_MECHANICS,
  BANK_AP_PRECALCULUS,
  BANK_AP_PSYCHOLOGY,
  BANK_AP_RESEARCH,
  BANK_AP_SEMINAR,
  BANK_AP_STATISTICS,
  BANK_AP_UNITED_STATES_GOVERNMENT_AND_POLITICS,
  BANK_AP_UNITED_STATES_HISTORY,
  BANK_AP_WORLD_HISTORY_MODERN,
]
